version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: K21h3fI5X!!
      MYSQL_DATABASE: calculator
    ports:
      - "3306:3306"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: food.py
    entrypoint: ["./entrypoint.sh"]
